baseurl                 = "blockfreight.io/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Blockfreight™ API Docs"
publishDir              = "docs"

# googleAnalytics       = "UA-126123494-1"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/"
    homepage            = "main"                        # What to call

# Metadata
    description         = "Blockfreight, Inc. [BFT:XCPC] " # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "images/twitter/blockfreight.png"       # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/#bftx_api"
    text = "bftx_api"